(define (square x)
    (* x x))
(define (sum-of-squares x y)
    (+ (square x) (square y)))
(define (sum-and-square x y z)
    (cond ((and (> x y) (> y z)) (sum-of-squares x y))
          ((and (< x y) (< y z)) (sum-of-squares y z))
          (else (sum-of-squares x z))))